name: KmpActions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-from-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Android
        run: ./gradlew assembleRelease 
      - name: Build Desktop
        run: ./gradlew packageDistributionForCurrentOS 

  build-from-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Desktop
        run: ./gradlew packageDistributionForCurrentOS
